"""empty message

Revision ID: 0a75dc478801
Revises: d5ed0493eaf3
Create Date: 2021-02-18 00:23:54.334681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a75dc478801'
down_revision = 'd5ed0493eaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('subject', sa.String(), nullable=True))
    op.drop_column('messages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'subject')
    # ### end Alembic commands ###
