"""empty message

Revision ID: 0fdac83b3358
Revises: 6b3ad5d9ea18
Create Date: 2021-02-24 00:50:14.095008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdac83b3358'
down_revision = '6b3ad5d9ea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('clients', 'namee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('namee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
