"""empty message

Revision ID: 54f5ac50bcca
Revises: bfea4ff0d767
Create Date: 2021-02-24 00:44:31.094842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f5ac50bcca'
down_revision = 'bfea4ff0d767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('tokenn', sa.String(), nullable=True))
    op.drop_constraint('tokens_token_key', 'tokens', type_='unique')
    op.create_unique_constraint(None, 'tokens', ['tokenn'])
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_unique_constraint('tokens_token_key', 'tokens', ['token'])
    op.drop_column('tokens', 'tokenn')
    # ### end Alembic commands ###
