"""empty message

Revision ID: 6b3ad5d9ea18
Revises: e92521fe1fba
Create Date: 2021-02-24 00:49:15.689874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3ad5d9ea18'
down_revision = 'e92521fe1fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('namee', sa.String(), nullable=True))
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'namee')
    # ### end Alembic commands ###
