"""empty message

Revision ID: bbffd6308e14
Revises: 6a61ca72275b
Create Date: 2021-02-18 00:26:43.579203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbffd6308e14'
down_revision = '6a61ca72275b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('messages', 'body_')
    op.add_column('notifications', sa.Column('body', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('header', sa.String(), nullable=True))
    op.drop_column('notifications', 'header_')
    op.drop_column('notifications', 'body_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('body_', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('header_', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'header')
    op.drop_column('notifications', 'body')
    op.add_column('messages', sa.Column('body_', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
