"""empty message

Revision ID: bfea4ff0d767
Revises: bbffd6308e14
Create Date: 2021-02-23 23:57:38.823748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfea4ff0d767'
down_revision = 'bbffd6308e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tokennotifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint('notifications_client_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'header')
    op.drop_column('notifications', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('header', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('notifications_client_id_fkey', 'notifications', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'title')
    op.drop_table('tokennotifications')
    op.drop_table('tokens')
    # ### end Alembic commands ###
