"""empty message

Revision ID: d5ed0493eaf3
Revises: 0a3c7a15d551
Create Date: 2021-02-17 23:16:04.791546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed0493eaf3'
down_revision = '0a3c7a15d551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('title', sa.Integer(), nullable=True))
    op.drop_column('messages', 'header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('header', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'title')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
