"""empty message

Revision ID: e92521fe1fba
Revises: 54f5ac50bcca
Create Date: 2021-02-24 00:44:58.391534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92521fe1fba'
down_revision = '54f5ac50bcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.String(), nullable=True))
    op.drop_constraint('tokens_tokenn_key', 'tokens', type_='unique')
    op.create_unique_constraint(None, 'tokens', ['token'])
    op.drop_column('tokens', 'tokenn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('tokenn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_unique_constraint('tokens_tokenn_key', 'tokens', ['tokenn'])
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###
